name: Transformers CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Transformers
        run: python3 -m pip install transformers torch

      - name: Download phi-2 model
        run: |
          sudo apt-get install git-lfs -y
          git lfs install
          git clone https://huggingface.co/microsoft/phi-2

      - name: Run run_transformers_phi2.py
        run: python3 run_transformers_phi2.py
